FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt ./
COPY requirements-ml.txt ./
RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential \
  && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements-ml.txt
COPY app ./app
COPY models ./models
EXPOSE 8001
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]

